name: WhatsApp Bot

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-whatsapp-message:
    runs-on: ubuntu-latest
    environment: Production  # Ensure GitHub loads env variables from the "Production" environment

    steps:
      - name: Debug Environment Variables
        run: |
          echo "CHAT_ID: ${{ vars.CHAT_ID }}"
          echo "SESSION_STORAGE_REPO: ${{ vars.SESSION_STORAGE_REPO }}"
          echo "Computed Clone URL: https://x-access-token:${{ secrets.WHATSAPP_SESSION_PAT }}@${{ vars.SESSION_STORAGE_REPO }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clone private storage repo
        run: |
          echo "Cloning session storage repository..."
          git clone https://x-access-token:${{ secrets.WHATSAPP_SESSION_PAT }}@${{ vars.SESSION_STORAGE_REPO }} session_data
          echo "Clone complete."

          echo "Listing session_data directory:"
          ls -la session_data

      - name: Move session data
        run: |
          echo "Moving session data to ~/.wwebjs_auth/"
          mkdir -p ~/.wwebjs_auth
          cp -r session_data/. ~/.wwebjs_auth/

          echo "Listing files in ~/.wwebjs_auth:"
          ls -la ~/.wwebjs_auth

      - name: Install dependencies
        run: npm install

      - name: Run WhatsApp bot
        env:
          CHAT_ID: ${{ vars.CHAT_ID }}
        run: |
          echo "Starting WhatsApp bot..."
          node index.js

      - name: Save session data back to private repo
        run: |
          echo "Saving session data back to repository..."
          cp -r ~/.wwebjs_auth/. session_data/
          
          echo "Listing updated session_data directory:"
          ls -la session_data
          
          cd session_data
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update WhatsApp session data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.WHATSAPP_SESSION_PAT }}@${{ vars.SESSION_STORAGE_REPO }} main
